# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.Sim_DDModel <- function(DDModel_, trials_) {
    .Call('_DDModeling_Generate_Modelprediction_rnd', PACKAGE = 'DDModeling', DDModel_, trials_)
}

.Fit_DDModel_rnd <- function(DDModel_, DDRep_) {
    .Call('_DDModeling_Fit_observed_data_rnd', PACKAGE = 'DDModeling', DDModel_, DDRep_)
}

.Fit_DDModel_grid <- function(DDModel_, DDRep_, gridpath) {
    .Call('_DDModeling_Fit_observed_data_grid', PACKAGE = 'DDModeling', DDModel_, DDRep_, gridpath)
}

.Get_ParComb <- function(DDModel_, wd, steps, nSplit) {
    invisible(.Call('_DDModeling_Calculate_Parameter_Combinations', PACKAGE = 'DDModeling', DDModel_, wd, steps, nSplit))
}

.Get_GRID <- function(calc_cluster) {
    invisible(.Call('_DDModeling_Grid_calc', PACKAGE = 'DDModeling', calc_cluster))
}

.DDRep_cpp <- function(DDModel_, RAW_) {
    .Call('_DDModeling_Generate_DDRep', PACKAGE = 'DDModeling', DDModel_, RAW_)
}

