# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.Sim_DDModel_rnd <- function(DDModel_, trials_) {
    .Call('_DDModeling_Generate_Modelprediction_rnd', PACKAGE = 'DDModeling', DDModel_, trials_)
}

.Sim_DDModel_par <- function(DDModel_, trials_, param_) {
    .Call('_DDModeling_Generate_Modelprediction_par', PACKAGE = 'DDModeling', DDModel_, trials_, param_)
}

.Fit_DDModel_rnd <- function(calc_cluster) {
    .Call('_DDModeling_Fit_observed_data_rnd', PACKAGE = 'DDModeling', calc_cluster)
}

.Fit_DDModel_grid <- function(calc_cluster) {
    .Call('_DDModeling_Fit_observed_data_grid', PACKAGE = 'DDModeling', calc_cluster)
}

.Fit_DDModel_DL <- function(calc_cluster) {
    .Call('_DDModeling_Fit_observed_data_DL', PACKAGE = 'DDModeling', calc_cluster)
}

.Get_ParComb_cpp <- function(DDModel_, wd, name, steps, nSplit) {
    invisible(.Call('_DDModeling_Calculate_Parameter_Combinations', PACKAGE = 'DDModeling', DDModel_, wd, name, steps, nSplit))
}

.Get_GRID_cpp <- function(calc_cluster) {
    invisible(.Call('_DDModeling_Grid_calc', PACKAGE = 'DDModeling', calc_cluster))
}

.GRID_to_DDRep <- function(calc_cluster) {
    .Call('_DDModeling_GRID_to_DDRep', PACKAGE = 'DDModeling', calc_cluster)
}

.DDRep_cpp <- function(DDModel_, RAW_) {
    .Call('_DDModeling_Generate_DDRep', PACKAGE = 'DDModeling', DDModel_, RAW_)
}

